# Generated by Django 4.2.2 on 2023-06-05 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='key',
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='pregunta',
            field=models.CharField(max_length=100),
        ),
    ]
